sudo: required
services:
  - docker

before_install:
  - docker build -t ahmedsparkle/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ahmedsparkle/react-test npm test

after_success:
  - docker build -t ahmedsparkle/multi-client ./client
  - docker build -t ahmedsparkle/multi-nginx ./nginx
  - docker build -t ahmedsparkle/multi-server ./server
  - docker build -t ahmedsparkle/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push ahmedsparkle/multi-client
  - docker push ahmedsparkle/multi-nginx
  - docker push ahmedsparkle/multi-server
  - docker push ahmedsparkle/multi-worker
